Add FT240X EEPROM. Remove FtdiMpsse impl for FT232R because it is unsupported
ftdi-rs/libftd2xx pull request #79
Opened 2024-08-29 11:41 UTC by Farmadupe

* Add FT240X EEPROM impls
* Factorize out mpsse functions from impl_boilerplate_for! macro, as not all devices support mpsse (FT240X, FT232R)
* Remove impl of FtdiMpsse for Ft232R, as the docs say it is not supported (breaking change)
* Inhibit tests for set_vid_pid functions on windows, as those functions are not available.

2024-09-01 23:56 UTC, newAM requested changes
Thanks!  Just a couple minor changes.

2024-09-01 23:56 UTC, newAM commented on src/lib.rs
> +use libftd2xx_ffi::FT_EEPROM_X_SERIES;
There's an import for all `libftd2xx_ffi` types below this, lump it in with those.

2024-09-01 23:56 UTC, newAM commented on src/types.rs
> +    FT_EEPROM_X_SERIES, FT_X_SERIES_CBUS_BCD_CHARGER, FT_X_SERIES_CBUS_BCD_CHARGER_N,
`FT_EEPROM_X_SERIES` should be with the other `FT_EEPROM_`'s

2024-09-02 09:22 UTC, Farmadupe commented
Comments addressed

2024-09-02 17:16 UTC, newAM approved these changes
Thanks!  Do you want a release with these changes?

2024-09-02 17:17 UTC, merged

2024-09-02 18:30 UTC, Farmadupe commented
A new release would be appreciated!

2024-09-06 03:32 UTC, newAM commented
Done in 0.33.0!